version: "3.9"

volumes: 
  mongodb_data:

services:
  sejutacita-test:
    container_name: sejutacita-test
    image: sejutacita-test
    ports:
      - 9000:9000
    environment: 
      - PORT=9000
      - DB_URI=mongodb+srv://ncksp:kCFt0nVi4wXklGDA@cluster0.peuzx.mongodb.net/sejutacita-test?retryWrites=true&w=majority 